### ISSUE TITLE
support .yaml.local?

### ISSUE THREAD

**Issue by mmetc** [crowdsecurity/cs-blocklist-mirror#17]

**Comment by LaurenceJJones** [comment]
Support environment expansion

**Comment by mmetc** [comment]
Hi @LaurenceJJones 

> Also Support environment expansion @mmetc

Is this something we do in other bouncers already, or only in the agent/lapi?

I'm asking because I'm not a fan of substituting environment variables ${LIKE_THIS} and I'd like to try another approach.

**Comment by LaurenceJJones** [comment]
@mmetc We do this for Crowdsec, and some of the bouncers people may expect the same behaviour

**Comment by mmetc** [comment]
I see. We are discussing alternatives.

**Comment by mmetc** [comment]
I've done this but we'd like to depend on stable versions, so it should be merged after 1.5

**Comment by mmetc** [comment]
yaml.local and variable expansion are done for all go bouncers
