### ISSUE TITLE
format error

### ISSUE THREAD

**Issue by Pick-Nick10** [crowdsecurity/cs-blocklist-mirror#29]
Hello,

I've been trying to implement this and it seems the option of "microtik" is not a valid option in the config.

I receive the following error: level=fatal msg="microtik format is not supported. Supported formats are 'plain_text'"

**Comment by LaurenceJJones** [comment]
The Microtik release is not release to our repositories yet. If you want to use it you would have to currently build it from source.

```
#go version # needs 1.20
cd /tmp
git clone https://github.com/crowdsecurity/cs-blocklist-mirror
cd cs-blocklist-mirror
make build
sudo systemctl stop crowdsec-blocklist-mirror
sudo cp crowdsec-blocklist-mirror $(which crowdsec-blocklist-mirror)
sudo systemctl start crowdsec-blocklist-mirror
```

**Comment by Pick-Nick10** [comment]
Oh I understand. This resolved the issue. Thank you!
