### ISSUE TITLE
stream api init failed

### ISSUE THREAD

**Issue by twist3dimages** [crowdsecurity/cs-blocklist-mirror#60]
I keep getting this message and can't get it to work. How would I diagnose this? I readded the bouncer and it does the same thing

**Comment by LaurenceJJones** [comment]
Check that you can connect to the URL that you specified in the configuration.

```
curl http://<api_url>/health
```

if you cant connect then something may be blocking the connection.

**Comment by twist3dimages** [comment]
it says Status ok
