### ISSUE TITLE
Separate IPv4 and IPv6 lists

### ISSUE THREAD

**Issue by cardosocristian** [crowdsecurity/cs-blocklist-mirror#67]
I'm using these two Crowdsec packages on FreeBSD:

crowdsec-1.4.6_2 CrowdSec lightweight and collaborative security engine
crowdsec-blocklist-mirror-0.0.1_5 CrowdSec Blocklist Mirror

I wanted to know if it would be possible to dismember the current list of IP's separately, where a list is only for IPv4 and another only for IPv6.
This makes it easier to use a firewall in IPv4 and IPv6.

**Comment by mmetc** [comment]
v0.0.2 was released for both linux and freebsd, do you need anything else?
