### ISSUE TITLE
change list name

### ISSUE THREAD

**Issue by alexanderek** [crowdsecurity/cs-blocklist-mirror#95]
Is it possible to change the list name for the Mikrotik format?  **list={list_name}**

**Comment by LaurenceJJones** [comment]
The format can be changed but is there any reason for the change?

**Comment by alexanderek** [comment]
I would like to specify a different name for the list instead of the default "CrowdSec"

**Comment by LaurenceJJones** [comment]
You can already provide a query parameter that allows the custom naming of the list

`?listname=foo`
